# 这是用户自定义解析列表,可以自行编辑
# 参数三可填0123分别对应:普通解析、json解析、并发多json解析、聚合解析。参数3不填默认0
# 名称,链接,类型,ua,flag,extra_headers (extra_headers格式: key:value|key:value)
# JSON解析排前面

777,https://jx.777jiexi.com/player/?url=,0,Mozilla/5.0,qiyi|imgo|爱奇艺|奇艺|qq|qq 预告及花絮|腾讯|youku|优酷|pptv|PPTV|letv|乐视|leshi|mgtv|芒果|sohu|xigua|fun|风行,
8090g,https://www.8090g.cn/jiexi/?url=,0,Mozilla/5.0,qiyi|imgo|爱奇艺|奇艺|qq|qq 预告及花絮|腾讯|youku|优酷|pptv|PPTV|letv|乐视|leshi|mgtv|芒果|sohu|xigua|fun|风行,
ik9,https://yparse.ik9.cc/index.php?url=,0,Mozilla/5.0,qiyi|imgo|爱奇艺|奇艺|qq|qq 预告及花絮|腾讯|youku|优酷|pptv|PPTV|letv|乐视|leshi|mgtv|芒果|sohu|xigua|fun|风行,
杰森,https://jx.jsonplayer.com/player/?url=,0,Mozilla/5.0,qiyi|imgo|爱奇艺|奇艺|qq|qq 预告及花絮|腾讯|youku|优酷|pptv|PPTV|letv|乐视|leshi|mgtv|芒果|sohu|xigua|fun|风行,
阳途,https://jx.yangtu.top/?url=,0,Mozilla/5.0,qiyi|imgo|爱奇艺|奇艺|qq|qq 预告及花絮|腾讯|youku|优酷|pptv|PPTV|letv|乐视|leshi|mgtv|芒果|sohu|xigua|fun|风行,
冰豆,https://bd.jx.cn/?url=,0,Mozilla/5.0,qiyi|imgo|爱奇艺|奇艺|qq|qq 预告及花絮|腾讯|youku|优酷|pptv|PPTV|letv|乐视|leshi|mgtv|芒果|sohu|xigua|fun|风行,
m3u8TV,https://jx.m3u8.tv/jiexi/?url=,0,Mozilla/5.0,qiyi|imgo|爱奇艺|奇艺|qq|qq 预告及花絮|腾讯|youku|优酷|pptv|PPTV|letv|乐视|leshi|mgtv|芒果|sohu|xigua|fun|风行,
听乐,https://jx.dj6u.com/?url=,0,Mozilla/5.0,qiyi|imgo|爱奇艺|奇艺|qq|qq 预告及花絮|腾讯|youku|优酷|pptv|PPTV|letv|乐视|leshi|mgtv|芒果|sohu|xigua|fun|风行,
虾米,https://jx.xmflv.com/?url=,0,Mozilla/5.0,qiyi|imgo|爱奇艺|奇艺|qq|qq 预告及花絮|腾讯|youku|优酷|pptv|PPTV|letv|乐视|leshi|mgtv|芒果|sohu|xigua|fun|风行,
虾米2,https://jx.xmflv.cc/?url=,0,Mozilla/5.0,qiyi|imgo|爱奇艺|奇艺|qq|qq 预告及花絮|腾讯|youku|优酷|pptv|PPTV|letv|乐视|leshi|mgtv|芒果|sohu|xigua|fun|风行,
云析,https://jx.yparse.com/index.php?url=,0,Mozilla/5.0,qiyi|imgo|爱奇艺|奇艺|qq|qq 预告及花絮|腾讯|youku|优酷|pptv|PPTV|letv|乐视|leshi|mgtv|芒果|sohu|xigua|fun|风行,
红狐,https://player.mrgaocloud.com/player/?url=,0,Mozilla/5.0,qiyi|imgo|爱奇艺|奇艺|qq|qq 预告及花絮|腾讯|youku|优酷|pptv|PPTV|letv|乐视|leshi|mgtv|芒果|sohu|xigua|fun|风行,
